### ISSUE TITLE
Troubles compiling master with clang

### ISSUE THREAD

**Issue by miconda** [sems-server/sems#126]
I noticed some referenced to clang in Makefile as well as a few pull requests/items on the tracker during the past, but I cannot get sems master compiling with it on debian testing or macos.

I used:

```
make PREFIX=/tmp/sems-dev CC=clang CXX=clang++ all
```

as well as

```
make PREFIX=/tmp/sems-dev CC=clang CXX=clang++ LD=clang all
```

On linux, it fails on linker:

```
clang: warning: argument unused during compilation: '-force_load sip/sip_stack.a' [-Wunused-command-line-argument]
/usr/bin/ld: AmThread.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:115: sems] Error 1
make[1]: Leaving directory '/home/porto/work/sip/sems/sems-dev/core'
make: *** [Makefile:27: modules] Error 2
```
This seems like missing pthread library linking option in a Makefile.

On macos, it goes further, but fails to compile the xmlrpc2di app:

```
make -C ../../../xmlrpc2di/xmlrpc++ libXmlRpc.a
clang++ -g -Wall  -O2  -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-307-ge4ec7143-dirty"' -DARCH='"x86_64"' -DOS='"macosx"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DBSD44SOCKETS -D__DARWIN_UNIX03 -I /opt/local/include -I ../../../../core -I../../../xmlrpc2di/xmlrpc++/src -I./src -fPIC -Wno-deprecated-declarations  -c -o src/XmlRpcClient.o src/XmlRpcClient.cpp
In file included from src/XmlRpcClient.cpp:2:
./src/base64.h:232:13: error: incomplete type 'std::__1::ios_base' named in nested name specifier
                                        _St |= _IOS_FAILBIT|_IOS_EOFBIT; return _First; // unexpected EOF
                                               ^~~~~~~~~~~~
./src/base64.h:35:29: note: expanded from macro '_IOS_FAILBIT'
#define _IOS_FAILBIT   std::ios_base::failbit
                       ~~~~~^~~~~~~~~~
```
I didn't want to dig in further before knowing if clang should be supported or not, to avoid spending much time on something that is supposed not to work anyhow.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> I didn't want to dig in further before knowing if clang should be
> supported or not, to avoid spending much time on something that is
> supposed not to work anyhow.

Daniel,

I personally have never tried to use clang++ to build sems, but don't
have anything against if someone provides tested, working pull requests
to make is possible.

Perhaps there is other people on the list with clang experience.

-- Juha

**Comment by miconda** [comment]
In the past, the items #6, #7, #8 and #9 were referencing clang++, but not sure if it is expected to work. Also, I don't have much time to spend on it, so this can be closed if main sems devs say it is not officially supported.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> In the past, the items #6, #7, #8 and #9 were referencing clang++, but
> not sure if it is expected to work. Also, I don't have much time to
> spend on it, so this can be closed if main sems devs say it is not
> officially supported.

I think there is currently no one in charge of sems and thus there is no
"official" opinion on anything related to it.  In order to start
supporting clang, someone should first make it work, which I don't
remember had ever been the case.

For a while there was very little development activity, and I tried to
keep sems together, since I'm heavily using it, Recently there has been
more activity, which is a good thing.

-- Juha

**Comment by lemenkov** [comment]
@miconda try using Cmake - it detects and builds with clang/LLVM very well. See our Travis-CI jobs where it was enabled for a while now:

* https://travis-ci.org/sems-server/sems/builds/535297737

**Comment by lemenkov** [comment]
@juha-h should be closed I believe. Since last year SEMS was rebuilt with clang regularly w/o any significant issues on two platforms (Ubuntu Linux and Mac OS X.

**Comment by juha-h** [comment]
OK, will close.
