### ISSUE TITLE
Send Transparent Media. (Open RTP)

### ISSUE THREAD

**Issue by amitiyer** [sems-server/sems#128]
Hello,

Currently i need to allow Transparent RTP stream to my customer, for example.
Customer is calling through Sems and from Sems to my provider.
Now on my customer’s switch, when they check the call information they are receiving Sems'sIP in the RTP streams. I need the Media to be transparent, When the customer checks the call info he needs to receive the vendors IP in the media info.

**Comment by juha-h** [comment]
amitiyer writes:

> Currently i need to allow Transparent RTP stream to my customer, for example.
> Customer is calling through Sems and from Sems to my provider.
> Now on my customer’s switch, when they check the call information they
> are receiving Sems'sIP in the RTP streams. I need the Media to be
> transparent, When the customer checks the call info he needs to
> receive the vendors IP in the media info.

What are you using sems for?  sems doesn't need to be on media path.
