### ISSUE TITLE
Incompatibility with Grandsteam phones with optional SRTP

### ISSUE THREAD

**Issue by nwhitehorn** [sems-server/sems#132]
Grandstream phones (hard and soft) have three security modes for SRTP:
* Disabled
* Enabled, but not Forced
* Forced

The first of these works fine, and the last of course completely fails since sems does not support SRTP (though it would be really nice if it did -- I notice the Yeti fork of sems has it). In the middle case, though, which I would expect to work, you get dead air. The issue is that in the second mode, the phone sends only a SAVP profile in the SDP; the "not forced" is that it will accept an AVP response with no cryptographic information from the remote end. The dead air is that sems accepts the INVITE but marks the SAVP profile inactive, leaving an apparently live call with no media. What Grandstream is doing is a clear violation of the specification, of course, but it would be nice if sems could handle it gracefully.

You can test this easily using the free Grandstream Wave mobile softphone.

**Comment by juha-h** [comment]
Nathan Whitehorn writes:

> The first of these works fine, and the last of course completely fails
> since sems does not support SRTP (though it would be really nice if it
> did -- I notice the Yeti fork of sems has it).

I would use rtpengine between the phone and sems.  rtpengine can do lots
of other media conversions too.

**Comment by juha-h** [comment]
I took a look at Yeti fork and the folks there have been really busy
with commits.

Does it make sense to keep on working on this project anymore?  Would it
make sense to switch to Yeti?

**Comment by lemenkov** [comment]
> on

Actually the difference is still not that big. I believe we still can merge @yeti-switch  fork back in a reasonable timeframe.

What SEMS lacks is roadmap and plans.

**Comment by juha-h** [comment]
Peter Lemenkov writes:

> Actually the difference is still not that big. I believe we still can
> merge @yeti-switch  fork back in a reasonable timeframe.

I'm trying to give yeti-switch sems a try, but at present it fails to
build according to its README.md.

If the build one day succeeds, I'm going to test if dsm app works with
it.  I don't care sbc app so much, because I can implement whatever sbc
functionality I need using dsm scripts.

> What SEMS lacks is roadmap and plans.

The main issue is that currently the project lacks a real leader, who
would push for such things.

**Comment by juha-h** [comment]
While trying to build yeti-switch, I noticed that it doesn't support
ZRTP, which to me is much more important than SRTP.  SRTP provides very
poor security for signaling.

**Comment by nwhitehorn** [comment]
I think it does? The ZRTP support is just conditionally enabled based on it finding a library, so the build system (which is crummy) might have just turned it off for you.

In any case, SRTP aside, it would be really nice if sems replied to a SAVP profile with an AVP counter-offer (and no encryption) rather than accepting these kinds of calls but disabling the audio.  I can do various hacks in the SIP proxy, but it would be nicer in SEMS. I'm not sure how to do that, though.

**Comment by juha-h** [comment]
Nathan Whitehorn writes:

> I think it does? The ZRTP support is just conditionally enabled based
> on it finding a library, so the build system (which is crummy) might
> have just turned it off for you.

When I asked, they replied: ZRTP support is not implemented.
  libzrtpcpp-dev was excess dependency. 

> In any case, SRTP aside, it would be really nice if sems replied to a
> SAVP profile with an AVP counter-offer (and no encryption) rather than
> accepting these kinds of calls but disabling the audio.  I can do
> various hacks in the SIP proxy, but it would be nicer in SEMS. I'm not
> sure how to do that, though.

Is your sems application terminating the media or just relaying it?

**Comment by nwhitehorn** [comment]
> Nathan Whitehorn writes:
> I think it does? The ZRTP support is just conditionally enabled based on it finding a library, so the build system (which is crummy) might have just turned it off for you.
> When I asked, they replied: ZRTP support is not implemented. libzrtpcpp-dev was excess dependency.

Weird. I haven't managed to build their code because of some problems with the build system, but I do see the ZRTP code there. Maybe it's dead and doesn't work anymore.

> In any case, SRTP aside, it would be really nice if sems replied to a SAVP profile with an AVP counter-offer (and no encryption) rather than accepting these kinds of calls but disabling the audio. I can do various hacks in the SIP proxy, but it would be nicer in SEMS. I'm not sure how to do that, though.
> Is your sems application terminating the media or just relaying it?

Terminating.

**Comment by juha-h** [comment]
Nathan Whitehorn writes:

> Weird. I haven't managed to build their code because of some problems
> with the build system, but I do see the ZRTP code there. Maybe it's
> dead and doesn't work anymore.

ZRTP works OK in sems-server/sems.

> > In any case, SRTP aside, it would be really nice if sems replied to
> > a SAVP profile with an AVP counter-offer (and no encryption) rather
> > than accepting these kinds of calls but disabling the audio. I can
> > do various hacks in the SIP proxy, but it would be nicer in
> > SEMS. I'm not sure how to do that, though.
> > Is your sems application terminating the media or just relaying it?
> 
> Terminating.

Perhaps someone has time to look into this.

**Comment by juha-h** [comment]
Nathan Whitehorn writes:

> Weird. I haven't managed to build their code because of some problems
> with the build system, but I do see the ZRTP code there. Maybe it's
> dead and doesn't work anymore.

ZRTP aside, dsm app doesn't compile either in yeti-switch/sems.  There
is stuff missing in their jsonrpc code and most likely also something
else.  So I have given up yeti-switch/sems as sems-server/sems
replacement.

**Comment by juha-h** [comment]
If sems does not support offered media transport protocol (it only support RTP/AVP), answer contains the offered transport, but port is set to zero. For example:
```
in offer
m=audio 13048 RTP/SAVP 96 8 0 101.

in answer
m=audio 0 RTP/SAVP 96.
```
The patch below makes sems reply with '488 Not Acceptable Here' if sems does not support any of the offered audio steams.
```
*** /usr/src/orig/sems/core/AmSession.cpp	2019-07-31 10:57:25.755392556 +0300
--- AmSession.cpp	2019-09-14 19:01:58.929255730 +0300
***************
*** 971,976 ****
--- 971,979 ----
      media_index++;
    }
  
+   if (audio_1st_stream)
+     throw Exception(488, "Not Acceptable Here");
+     
    return true;
  }
  
```
Give it a try.

**Comment by juha-h** [comment]
No response, but I want to get rid of this by commit 05ee73e2..a8c37505.
