### ISSUE TITLE
Travis-CI PR statuses are gone 

### ISSUE THREAD

**Issue by lemenkov** [sems-server/sems#152]
It seems that we've lost integration with Travis-Ci again. It does builds PRs and merges but I can't see it at GitHub anymore:

* https://travis-ci.org/github/sems-server/sems/builds
* https://travis-ci.org/github/sems-server/sems/pull_requests

@juha-h could you please take a look? Perhaps some auth tokens got expired or something similar.

**Comment by juha-h** [comment]
I can see them.  Can you see them now?

**Comment by juha-h** [comment]
I'll close this since I can see the builds and PRs even when not logged in  to GitHub.

**Comment by lemenkov** [comment]
Looks good now.
