### ISSUE TITLE
multilanguage. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sems-server/sems#157]
How do I add multi language support for 
voicebox, voicemail and ann-recorder ?

**Comment by juha-h** [comment]
johandeclercqdemocon writes:

> How do I add multi language support for 
> voicebox, voicemail and ann-recorder ?

I have done it in my apps by adding a param that contains the language
code and then based on that select the proper message from the database.
See EarlyAnnounce.cpp for an example.
