### ISSUE TITLE
How to disable RTP/SDP processing?

### ISSUE THREAD

**Issue by mkezys** [sems-server/sems#161]
Hello,

We are trying to use SEMS as B2BUA with Kamailio, when media is handled by RTPEngine. I can't find a way to turn off SDP processing on the SEMS.

I have such settings in sbcprofile

    enable_rtprelay=no
    rtprelay_force_symmetric_rtp=no

and sems.conf

    enable_rtprelay=no
    force_symmetric_rtp=no

On start SEMS shows (apart other stuff):

    [readConfiguration, AmConfig.cpp:543] INFO:  Not Enabling RTP mux port.
    [main, sems.cpp:599] INFO:  Starting media processor
    [main, sems.cpp:612] INFO:  Starting RTP receiver
    [readFromConfiguration, SBCCallProfile.cpp:503] INFO:  SBC:      RTP relay enabled: 'no'

During the call:

    [setRtpRelayMode, AmB2BSession.cpp:902] DEBUG:  enabled RTP relay mode for B2B call 
    [parse_sdp_line_ex, AmSdp.cpp:576]         DEBUG:  parsing SDP message...

What is the correct way to disable RTP/SDP processing at all?

**Comment by juha-h** [comment]
mkezys writes:

> During the call:
> 
>     [setRtpRelayMode, AmB2BSession.cpp:902] DEBUG:  enabled RTP relay mode for B2B call 

The message is misleading.  It does not necessarily mean that rtp relay
is enabled:
```
void AmB2BSession::setRtpRelayMode(RTPRelayMode mode)
{
  DBG("enabled RTP relay mode for B2B call '%s'\n",
      getLocalTag().c_str());

  rtp_relay_mode = mode;
}
```
Possible values of mode are:
```
  enum RTPRelayMode {
    /* audio will go directly between caller and callee
     * SDP bodies of relayed requests are filtered */  
    RTP_Direct,

    /* audio will be realyed through us
     * SDP bodies of relayed requests are filtered 
     * and connection addresses are replaced by us
     */
    RTP_Relay,

    /*
     * similar to RTP_Relay, but additionally transcoding 
     * might be used depending on payload IDs 
     */
    RTP_Transcoding
  };
```
Change the function like this and try what you then get to syslog:
```
void AmB2BSession::setRtpRelayMode(RTPRelayMode mode)
{
  DBG("set RTP relay mode for B2B call '%s' to '%d'\n",
      getLocalTag().c_str(), mode);

  rtp_relay_mode = mode;
}
```

**Comment by mkezys** [comment]
Thank you for your prompt reply. I got: 

    DEBUG:  set RTP relay mode for B2B call '4A2D2FEF-5F808ECD00087288-16A69700' to '0'

means RTP_Direct, which is good. But then it's unclear why SDP is parsed?

Also: 

    DEBUG:  found unknown value for media attribute 'direction'

and then we got out SDP with a=direction:both "improved".

Should it be that in RTP_Direct mode it should not touch SDP at all?

**Comment by juha-h** [comment]
mkezys writes:

> Should it be that in RTP_Direct mode it should not touch SDP at all?

There may be signaling reasons to parse and modify SDP even when rtp is
not relayed.

**Comment by mkezys** [comment]
If I understand correctly, currently there is no way to stop parsing/editing SDP?

**Comment by juha-h** [comment]
mkezys writes:

> If I understand correctly, currently there is no way to stop
> parsing/editing SDP?

I haven't checked if SDP is always parsed, but it shouldn't matter
except perhaps a small performance penalty.

**Comment by mkezys** [comment]
We are trying to solve no-audio problem and I am worried about SEMS modifying SDP, when it should not be doing this in our case where we want to use it as B2BUA for signaling only.
Anyway, thank you! You saved a lot of time for me.

**Comment by mkezys** [comment]
One more question if I may - if I would like to implement an option for SEMS, to stop parsing/changing SDP, where could be a good place to start in the SEMS code? Adding an option is clear, but what about the SDP?

**Comment by juha-h** [comment]
mkezys writes:

> One more question if I may - if I would like to implement an option
> for SEMS, to stop parsing/changing SDP, where could be a good place to
> start in the SEMS code? Adding an option is clear, but what about the
> SDP?

I don't understand why would you like to prevent parsing of SDP, since
parsing alone doesn't change anything in the SDP.

**Comment by mkezys** [comment]
Apart from parsing, SEMS modifies SDP in RTP_Direct mode.

I found out that SEMS adds a=direction:both to the SDP for some reason. 

And I am afraid SEMS changes SDP in other ways which I still did not found and messes with the media flow.

That's why I want to stop it parsing/changing SDP at all.

**Comment by juha-h** [comment]
mkezys writes:

> Apart from parsing, SEMS modifies SDP in RTP_Direct mode.
> 
> I found out that SEMS adds a=direction:both to the SDP for some reason. 
> 
> And I am afraid SEMS changes SDP in other ways which I still did not found and messes with the media flow.
> 
> That's why I want to stop it parsing/changing SDP at all.

Well, if you don't trust sems with SDP handling, then you cannot trust
it for anything else either, e.g. messing up headers, etc.

**Comment by mkezys** [comment]
This is not about trust. I see no need for SEMS to handle media, when not necessary and I would like to have an option to turn it off. In our setup, SEMS makes wonders with signaling and I am super happy about it. If there is a way to help with this project - let me know. Any thoughts on merging it with the yeti-switch? I could finance part of it (depends on the costs).

**Comment by juha-h** [comment]
mkezys writes:

> This is not about trust. I see no need for SEMS to handle media, when
> not necessary and I would like to have an option to turn it off. In
> our setup, SEMS makes wonders with signaling and I am super happy
> about it. If there is a way to help with this project - let me
> know. Any thoughts on merging it with the yeti-switch? I could finance
> part of it (depends on the costs).

I checked Yeti a few months ago and there is no chance to merge it to
sems.  You need to choose which one to use.

Regarding turning off parsing of SDP, I haven't checked if it would be
easy or if sbc code assumes that it is parsed, because some its
capabilities do require access and modification of the SDP, for example,
putting call on hold.

**Comment by mkezys** [comment]
Thank you for your answers.
