### ISSUE TITLE
[SEMS] Server Internal Error on re-INVITE w/o SDP

### ISSUE THREAD

**Issue by denyspozniak** [sems-server/sems#182]
Hello!

I have noticed that if you send a SIP re-INVITE without SDP towards the SEMS that has Contents below,
then it will respond with a `500 Server Internal Error`.
```
INVITE R-URI SIP/2.0
...
Content-Type: application/sdp    
Content-Length: 0
```

I believe having an `application/sdp` should not be handled this way (https://www.rfc-editor.org/rfc/rfc3261#section-20.15):

`The Content-Type header field MUST be present if
   the body is not empty.  If the body is empty, and a Content-Type
   header field is present, it indicates that the body of the specific
   type has zero length.
`

Only this is in the logs:
```
[/builddir/build/BUILD/sems-1.7.1/apps/sbc/SBCCallProfile.cpp:1395] ERROR:  Ignoring unknown payload found in
 call profile: 'gsm/8000'
[/builddir/build/BUILD/sems-1.7.1/core/AmB2BSession.cpp:810] ERROR:  dlg->sendRequest() failed
```
![image](https://user-images.githubusercontent.com/22612345/164785296-27b1bc82-128f-4f0b-b6f2-47ba02624a07.png)

**PS**: I have prepared sipp scripts to reproduce, if necessary, I can send them individually.

**Comment by denyspozniak** [comment]
debug [sems_PR182.txt](https://github.com/sems-server/sems/files/8552539/sems_PR182.txt):
![image](https://user-images.githubusercontent.com/22612345/165042601-254019e4-3a67-45b8-8f02-f5b756a45bd5.png)

**Comment by juha-h** [comment]
It may be so that some content types can have zero length, but is SDP such content type?  Usually, if there is no media, SDP still is there with IP 0.0.0.0.

**Comment by juha-h** [comment]
SDP RFC 8866 tells:

[5. ](https://www.rfc-editor.org/rfc/rfc8866.html#section-5)[SDP Specification](https://www.rfc-editor.org/rfc/rfc8866.html#name-sdp-specification)

    An SDP description is denoted by the media type "application/sdp" 
    ...
    An SDP description consists of a session-level section followed by zero or more media descriptions. 

 And according to section 9 SDP Grammar, session-description cannot be empty.

So I would suggest fixing the UA.
