### ISSUE TITLE
rport/RFC 3581 related bug (with for example Broadworks)

### ISSUE THREAD

**Issue by dtryba** [sems-server/sems#193]
When SEMS receives a re-Invite (on hold) from Broadworks, replies will be send back to the the source of the re-Invite. Broadworks uses a random UDP port to send messages to other SIP entities, but will ignore responses to that random port and expects the response to be to send to 5060.

I'm not sure if RFC 3261 says that the sender MUST be able to receive responses on this random port. RFC 3581 mentions that the response address/port should be based on the Via (in this situation that would be port 5060). But reality is that Broadworks ignore the responses to the random port and that other SIP server/proxy like Asterisk and Kamailio do the "correct" thing and send replies to 5060. SEMS sends the replies to the source port even though it comes to the conclusion not to use rport for the replies.

Version: Sip Express Media Server (1.7-dev-459-g59bc218e-dirty (x86_64/linux))
The config is close to the defaults in the project. Only changed the listening port and only load the sbc module with a transparant config (see the zip)

request (line 698 in attached txt):
```
 [#7f5b85227700/428123] [run, udp_trsp.cpp:355] DEBUG: vv M [|] u recvd msg via UDP from 10.128.34.100:52174 vv
--++--
INVITE sip:10.128.34.97:5080;transport=udp SIP/2.0
Via:SIP/2.0/UDP 10.128.34.100;branch=z9hG4bKBroadWorks.1sjtpmm-10.128.34.97V5080-0-616564471-994045624-1674122891254
From:<sip:+318510XXXXX@sip.itco.nl>;tag=994045624-1674122891254
To:"+318801XXXXX"<sip:+318801XXXXX@sip.itco.nl>;tag=6274FACC-63C9168A000AF127-8491E700
Call-ID:3428D2C2-63C9168A000AF129-8491E700
CSeq:616564471 INVITE
Contact:<sip:10.128.34.100:5060>
Allow:ACK,BYE,CANCEL,INFO,INVITE,OPTIONS,PRACK,REFER,NOTIFY,UPDATE
Supported:
Accept:application/media_control+xml,application/sdp,application/x-broadworks-call-center+xml
Max-Forwards:30
Content-Type:application/sdp
Content-Length:390
```

response:
```
 [#7f5b8491e700/428155] [send_request, trans_layer.cpp:1300] DEBUG:  Sending to 10.128.34.97:5060 <INVITE sip:sip118363@10.128.0.19:5060 SIP/2.0
Via: SIP/2.0/UDP 10.128.34.97:5080;branch=z9hG4bKoH9OBast;rport
From: <sip:+318510XXXXX@sip.itco.nl>;tag=6B4BDC2B-63C9168A000AC06E-84F24700
To: "+318801XXXXX" <sip:+318801XXXXX@sip.itco.nl>;tag=1c1204288727
CSeq: 10 INVITE
Call-ID: 205760066119120231088@10.128.0.19
Route: <sip:10.128.34.97;lr;ftag=1c1204288727;did=407.09d2;sems=yes>, <sip:185.61.68.106;lr;ftag=1c1204288727;did=407.4741;vsf=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA--;vst=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-->
Max-Forwards: 29
Allow: ACK,BYE,CANCEL,INFO,INVITE,OPTIONS,PRACK,REFER,NOTIFY,UPDATE
Accept: application/media_control+xml,application/sdp,application/x-broadworks-call-center+xml
Content-Type: application/sdp
Contact: <sip:10.128.34.97:5080;transport=udp>
Content-Length: 408
```

**Comment by dtryba** [comment]
[sems.zip](https://github.com/sems-server/sems/files/10456090/sems.zip)
[sems-bug.txt](https://github.com/sems-server/sems/files/10456093/sems-bug.txt)

**Comment by dtryba** [comment]
![Screenshot_20230119_121202](https://user-images.githubusercontent.com/37694237/213427977-23650508-ed65-4f6c-a200-0e79b803e0e0.png)

**Comment by dtryba** [comment]
![Screenshot_20230119_121522](https://user-images.githubusercontent.com/37694237/213428593-f027e1fd-1cec-439c-9380-6d27e92fee0b.png)
The same scenario when having SEMS use Kamailio (with next_hop=10.128.34.97:5060) to route the messages "correctly".

**Comment by denyspozniak** [comment]
@dtryba , did you try to set parameters below?

```
# optional parameter: sig_sock_opts=option,option,option,...
#
# - signaling socket options
#      o force_via_address         - force sending replies to 1st Via
#      o no_transport_in_contact   - do not add transport to contact in replies
#
# Example:
#  sig_sock_opts=force_via_address,no_transport_in_contact
```
