### ISSUE TITLE
sems transparent sbc contact problem

### ISSUE THREAD

**Issue by pumper** [sems-server/sems#206]
Hi I am new to sems and I want to use it as sbc in transparent profile. my problem is that for the REGISTER message I used: enable_reg_caching=yes 
but contact header that sent to the sip proxy server is something like :
Contact: <sip:8f79c6e0cf27a86e@192.168.111.111;transport=udp>;expires=600
I mean sems change user number to a hash string. but my carrier proxy server after registeration don't send calls to the user because it cant find the user. how to resolve this? I need the contact to be with user number for example 
Contact: <sip:12345678@192.168.111.111;transport=udp>;expires=600
every change i made in the configuration file dosnt affect contact header.

**Comment by dmitry-sinina** [comment]
I think it is not possible without patching SEMS. But your provider behave incorrectly - protocol not requires specific username for Contact Uri.
