### ISSUE TITLE
g729 codec compilation problem

### ISSUE THREAD

**Issue by 46labs** [sems-server/sems#21]
It appears this block in the new g729.c is incorrect and fails compilation.

static amci_codec_fmt_info_t[] gsm_fmt_description = { { AMCI_FMT_FRAME_LENGTH, 20 },
                                                       { AMCI_FMT_FRAME_SIZE, 160 },
                                                       { AMCI_FMT_ENCODED_FRAME_SIZE, 33 },
                                                       { 0, 0 }
};

**Comment by mslehto** [comment]
I guess this commit is related: 52914cdc528289d420673ac7ca7b08068dbd2995

**Comment by mslehto** [comment]
Quick test on my system fails in missing #include usc.h

**Comment by mslehto** [comment]
Hi @46labs. Is refered commit [https://github.com/sems-server/sems/commit/52914cdc528289d420673ac7ca7b08068dbd2995] working for you?

**Comment by 46labs** [comment]
Yes, this appears to be working!
