### ISSUE TITLE
 BYE from B2B callee terminates whole call before B2B.otherBye() transition is executed

### ISSUE THREAD

**Issue by juha-h** [sems-server/sems#27]
According to dsm_syntax.txt:

 B2B.sendReinvite(generate_sdp [, string extra_headers])
   send a reinvite in caller leg (first leg), e.g. to 
   reconnect first leg after B2B.otherBye received. 
   generate_sdp can be 'true' or 'false'
   (B2B.sendReinvite(true) recommended)

The problem is that BYE from callee leg has already already terminated
the whole call before B2B.otherBye() transition is executed and it is therefore too late to call B2B.sendReinvite(). In the test I have

transition "bye on other leg" conn - B2B.otherBye() / {
   log(2, received bye from callee);
   B2B.sendReinvite(true);
} -> thanks_for_calling;

and I get to syslog:

Feb  9 03:58:28 lohi sems[11512]: [#7f509b8f8700] [runEvent, DSMStateEngine.cpp:668] DEBUG:    >>>running 2 actions of transition 'bye on other leg'
Feb  9 03:58:28 lohi sems[11512]: [#7f509b8f8700] [runactions, DSMStateEngine.cpp:316] DEBUG:  running 2 DSM action elements
Feb  9 03:58:28 lohi sems[11512]: [#7f509b8f8700] [runactions, DSMStateEngine.cpp:321] DEBUG:  executing 'log(2, received bye from callee)'
Feb  9 03:58:28 lohi sems[11512]: [#7f509b8f8700] [execute, DSMCoreModule.cpp:624] INFO: FSM:  'received bye from callee'
Feb  9 03:58:28 lohi sems[11512]: [#7f509b8f8700] [runactions, DSMStateEngine.cpp:321] DEBUG:  executing 'B2B.sendReinvite(true)'
Feb  9 03:58:28 lohi sems[11512]: [#7f509b8f8700] [reinvite, AmSipDialog.cpp:600] DEBUG:  reinvite(): we are not connected (status=Disconnecting). do nothing!

How to prevent B2B.otherBye() event from terminating the call?  Is there
some magic missing from the above B2B.sendReinvite description?

It would be nice to get this solved before 1.7 is out. The whole test
diag is below.

-- Juha

---

import(mod_mysql);
import(mod_utils);

initial state START;

transition "sess start" START - sessionStart / {
  log(2, Entering test);
  playFile(/tmp/greeting.wav);
} -> lobby;

state lobby;

transition "bye in lobby recvd" lobby - hangup / stop(false) -> end;

state end;

transition "lobby to connect" lobby - noAudioTest / {
   B2B.connectCallee("sip:jh@test.tutpro.com", "sip:jh@test.tutpro.com");
} -> waitconnect;

state waitconnect;
state conn;

transition "bye" (waitconnect, conn) - hangup / { 
   log(2, bye while connecting);
   B2B.terminateOtherLeg(); 
   stop(false);
} -> end;

transition "prov reply" waitconnect - B2B.otherReply(#code < 200) / { 
   log(2, received provisional reply);
} -> waitconnect;

transition "positive reply" waitconnect - B2B.otherReply(#code < 300) / { 
   log(2, received positive reply);
   flushPlaylist();
   disconnectMedia();
} -> conn;

transition "negative reply" waitconnect - B2B.otherReply() / { 
   log(2, received negative reply);
   stop(false);
} -> end;

transition "bye on other leg" conn - B2B.otherBye() / {
   log(2, received bye from callee);
   B2B.sendReinvite(true);
} -> thanks_for_calling;

state thanks_for_calling enter {
  info("==== entering thanks_for_calling");
  playFile("/tmp/thanks_for_calling.wav");
};

transition "audio_ends" thanks_for_calling - noAudio / {
  info("==== audio ends at thanks_for_calling");
  stop(true);
} -> end;

transition "bye recvd" (START, end, thanks_for_calling) - hangup / {
   log(2, keep checker happy);
   stop(false);
} -> end;

**Comment by sanchi** [comment]
hey, please retest with the change to the DSM script as in the doc, sth like:
transition "bye on other leg" conn - B2B.otherBye() / {
 log(2, received bye from callee);
 set(#processed=true);
 dlg.relayReply(200, "OK");
 B2B.sendReinvite(true);
 connectMedia();
} -> thanks_for_calling;

**Comment by sanchi** [comment]
...i'm only sceptical that an ivr script (ivr python app) can do the same, as I think it can't send the 200 to the BYE.

**Comment by juha-h** [comment]
Stefan Sayer writes:

> ...i'm only sceptical that an ivr script (ivr python app) can do the
> same, as I think it can't send the 200 to the BYE.

Stefan,

Thank you very much for allowing handling of B2B.otherBye in dsm
scripts!

I don't anymore know about ivr python apps, since I have converted all
of mine to dsm.  I was also planning to convert all my B2B dsm scripts
to use mod_dlg, but after this commit, I don't need to do it.

I'll test the commit and will report if I found issues.

-- Juha

**Comment by juha-h** [comment]
Stefan Sayer writes:

> hey, please retest with the change to the DSM script as in the doc, sth like:
> transition "bye on other leg" conn - B2B.otherBye() / {
>  log(2, received bye from callee);
>  set(#processed=true);
>  dlg.relayReply(200, "OK");
>  B2B.sendReinvite(true);
>  connectMedia();
> } -> thanks_for_calling;

after receiving bye from callee, sems sends re-invite to caller with sdp
lines

m=audio 40002 RTP/AVP 105 101 102 103 104 8 0 3 2 9 96 97 98 99 100
a=rtpmap:105 opus/48000/2
...

and gets back in 200 ok sdp lines:

m=audio 10872 RTP/AVP 105 103 8 0 96
b=AS:128
a=rtpmap:105 opus/48000/2

this looks all fine and audio file is played fine to the caller, but
during the play i get to syslog lots of these:

Apr 13 12:26:35 lohi sems[23455]: [#7f0315c78700] [setCurrentPayload, AmRtpAudio.cpp:376] ERROR:  Could not set current payload: payload 105 unknown to this stream

i noticed that sems sends re-invite to the caller before it sends 200 ok
to bye if that matters anything.

-- juha

**Comment by sanchi** [comment]
can you please attach a full DBG log file + ngrep trace for such a call?

**Comment by juha-h** [comment]
Stefan Sayer writes:

> can you please attach a full DBG log file + ngrep trace for such a
> call?

Attached,

-- Juha

**Comment by juha-h** [comment]
I returned back to this old issue and finally got the script shown in the first comment working.  Stefan's commit did solve the problem (whole call is not anymore terminated when callee hangs up).  Handling of B2B.otherBye() event started to work OK, once I removed from it statement dlg.relayReply(200, "OK").  

Here is the working version:
 ```transition "bye on other leg" conn - B2B.otherBye() / {
  log(2, received bye from callee);
  set(#processed=true);
  dlg.relayReply(200, "OK");
  B2B.sendReinvite(true);
  connectMedia();
 } -> thanks_for_calling;```

Thanks to Stefan for the commit.

**Comment by juha-h** [comment]
I'll try again.  Looks like triple quotes need to be on their own lines:
```
transition "bye on other leg" conn - B2B.otherBye() / {
  log(2, received bye from callee);
  set(#processed="true");
  B2B.sendReinvite(true);
  connectMedia();
} -> thanks_for_calling;
```
