### ISSUE TITLE
Sems doesnt support latest Ubuntu LTS Xenial

### ISSUE THREAD

**Issue by 46labs** [sems-server/sems#32]
Sems wont compile on Xenial. The compile will complete, but wont produce a sems binary.

**Comment by 46labs** [comment]
Lots of these in compilation:

../../core/../Makefile.defs:374: warning: overriding recipe for target '/'
../../core/../Makefile.defs:371: warning: ignoring old recipe for target '/'
../../core/../Makefile.defs:377: warning: overriding recipe for target '/'
../../core/../Makefile.defs:374: warning: ignoring old recipe for target '/'
../../core/../Makefile.defs:380: warning: overriding recipe for target '/'
../../core/../Makefile.defs:377: warning: ignoring old recipe for target '/'

**Comment by lemenkov** [comment]
@46labs , try cmake :)

**Comment by 46labs** [comment]
sip: Deprecation warning: py_sems.sip:1: %Module version number should be specified using the 'version' argument
sip: AmMimeBody.sip:88: AmMimeBody::getParts() unsupported function return type - provide %MethodCode and a C++ signature
Error: Unable to open "/usr/local/src/sems/apps/py_sems/sip/py_sems.sbf"
-- Configuring done
CMake Error at apps/py_sems/sip/CMakeLists.txt:20 (ADD_LIBRARY):
  Cannot find source file:

    sippy_sems_libAmAudioEvent.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "sip".
CMake Error: CMake can not determine linker language for target: sip

**Comment by 46labs** [comment]
make[2]: Leaving directory '/usr/local/src/sems-cmake'
make -f apps/py_sems/sip/CMakeFiles/sip.dir/build.make apps/py_sems/sip/CMakeFiles/sip.dir/build
make[2]: Entering directory '/usr/local/src/sems-cmake'
make[2]: *** No rule to make target 'apps/py_sems/sip/CMakeFiles/sip.dir/build'.  Stop.
make[2]: Leaving directory '/usr/local/src/sems-cmake'
CMakeFiles/Makefile2:2522: recipe for target 'apps/py_sems/sip/CMakeFiles/sip.dir/all' failed
make[1]: *** [apps/py_sems/sip/CMakeFiles/sip.dir/all] Error 2
make[1]: Leaving directory '/usr/local/src/sems-cmake'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by 46labs** [comment]
Removing all modules but SBC from sems allows cmake to compile, but sems wont start:

 [16444//usr/local/src/sems/core/AmPlugIn.cpp:298] ERROR:  AmPlugIn::loadPlugIn: /usr/local/lib/sems/plug-in//sbc.so: /usr/local/lib/sems/plug-in//sbc.so: undefined symbol: _ZTI14_RegisterCache
 [16444//usr/local/src/sems/core/AmPlugIn.cpp:206] ERROR:  while loading plug-in '/usr/local/lib/sems/plug-in//sbc.so'

**Comment by 46labs** [comment]
@lemenkov you had a fix for this with Fedora. Can you shed light on fixing the "undefined symbol: _ZTI14_RegisterCache" issue? Here #20

**Comment by lemenkov** [comment]
Hello! It certainly does now! Take a look at the Travis-CI jobs - they all built on top of 14.04 and 16.04.

@juha-h technically this is resolved.

**Comment by hecko** [comment]
Can we close this ticket/issue please?
