### ISSUE TITLE
error on compile the opus codecs

### ISSUE THREAD

**Issue by alochym01** [sems-server/sems#33]
make[3]: Entering directory `/mnt/sems/core/plug-in/opus'
gcc -MMD -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-68-g1b17939-dirty"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DPROPAGATE_COREDUMP_SETTINGS -I. -fno-strict-aliasing -DUSE_INTERNAL_RESAMPLER -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -I ../.. -I ../../amci  -Wall -fPIC -g  -O2 -Wall  -c opus.c -o opus.o
opus.c:49:23: fatal error: opus/opus.h: No such file or directory
 #include <opus/opus.h>
                       ^
compilation terminated.
make[3]: *** [opus.o] Error 1
make[3]: Leaving directory `/mnt/sems/core/plug-in/opus'

please check the source code
thanks

**Comment by alochym01** [comment]
fix it by install opus-devel package

thanks

**Comment by Mohit-Ak** [comment]
```sudo apt-get install libopus-dev```
