### ISSUE TITLE
request for sems opus rpm centos 7

### ISSUE THREAD

**Issue by alochym01** [sems-server/sems#34]
Hi

there is no sems opus codec for rpm package

this is the yum search sems --enablerepo epel-testing
sems-dsm.x86_64 : The state machine interpreter for SEMS
sems-g722.x86_64 : G.722 support for SEMS
sems-gsm.x86_64 : GSM support for SEMS
sems-ilbc.x86_64 : iLBC support for SEMS
sems-ivr.x86_64 : IVR functionality for SEMS
sems-speex.x86_64 : Speex support for SEMS
sems-xmlrpc2di.x86_64 : XMLRPC interface for SEMS
sems.x86_64 : SIP Express Media Server, an extensible SIP media server
sems-conf_auth.x86_64 : Conference with authorization
sems-conference.x86_64 : Conferencing application
sems-diameter_client.x86_64 : A simple DIAMETER client implementation
sems-early_announce.x86_64 : Early announce application
sems-mailbox.x86_64 : Mailbox application
sems-pin_collect.x86_64 : Collects a PIN

it would be greate to have the sems-opus package 

thank you

**Comment by lemenkov** [comment]
@alochym01 thanks for the proposal! I'll try to make a build in a few days!

**Comment by lemenkov** [comment]
Unfortunately it took much longer than I thought initially. Anyway here it is:

* https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-2138d337eb

**Comment by lemenkov** [comment]
@juha-h I believe this can be closed now.
