### ISSUE TITLE
Sems 1.7-dev memory leak

### ISSUE THREAD

**Issue by 46labs** [sems-server/sems#49]
We are running into a fairly serious memory leak in the latest version of SEMS (1.7 dev). Recently updated to latest commit today, the leak is still happening. Can you suggest how we can begin diagnosing this?

**Comment by dunst0** [comment]
You can try valgrind for getting some information.

**Comment by dunst0** [comment]
Can you please give some information to your setup which gives you the serious memory leaks. Because right now I am digging deep into the core source code and doing some fixing and reformatting.

**Comment by lemenkov** [comment]
This ticket should be closed I'm afraid. Not much information for moving any further.

@juha-h could you please take a look.
