### ISSUE TITLE
build system does not fail on errors

### ISSUE THREAD

**Issue by linuxmaniac** [sems-server/sems#5]
AFAIK build does not fail because there are some known problems with some old modules but I think we should disable those failing modules/plugins by default and do not skip make errors.

From my POW it is quite important to know that a build is a success without having to look over all the output

**Comment by dunst0** [comment]
Which is the prefered build system CMake or plain old Makefiles,
becaus the Makefiles just ignores settings in the Makefile.defs

> From my POW it is quite important to know that a build is a success without having to look over all the output

I agree with that.

**Comment by lemenkov** [comment]
@dunst0 CMake is still experimental. That said feel free to use it - I'm using it for several years and feel fine :)

**Comment by guillemj** [comment]
I've fixed this, the actual build errors, and few others things that were preventing building SEMS on a current Debian unstable system. We are testing this locally, and once it looks good, I'll publish the changes.

**Comment by guillemj** [comment]
Oh, it seems I lost track of this. The changes are now on https://github.com/sems-server/sems/pull/65

**Comment by linuxmaniac** [comment]
Fixed by @guillemj at #65
