### ISSUE TITLE
opus payload from SEMS  is incorrect 

### ISSUE THREAD

**Issue by linhtn121** [sems-server/sems#50]
I have a sip message:
```
[Log] Wed Nov 16 2016 16:50:37 GMT+0700 (ICT) | sip.transport | received WebSocket text message: (sip.js, line 2893)

INVITE sip:5f9kqaqa@42.116.8.164:56623;transport=ws SIP/2.0
Via: SIP/2.0/WS 42.117.9.23:7080;branch=z9hG4bK0a2f.36d7b712.0
From: sip:16666@42.117.9.23;tag=4C582305-582C2B9B000E95F2-974F4700
To: sip:8669@42.117.9.23
CSeq: 10 INVITE
Call-ID: DLGCH_fkFVWBUMZBBiRV1cEHsSag1AVV4WcGUVeV1cWWcPZGR/QA--
Max-Forwards: 69
Supported: replaces, outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
User-Agent: LinphoneAndroid/3.2.0 (belle-sip/1.5.0)
Content-Type: application/sdp
Contact: <sip:42.117.9.23:7080;transport=ws;did=28b.cdb60a67>
Content-Length: 577

v=0
o=16666 2171 2933 IN IP4 192.168.1.48
s=Talk
c=IN IP4 42.117.9.24
t=0 0
m=audio 32386 UDP/TLS/RTP/SAVPF 102
a=rtpmap:102 opus/48000
a=direction:both
a=sendrecv
a=rtcp:32387
```

>
According RFC 7587
7.  SDP Considerations

   The information described in the media type specification has a
   specific mapping to fields in the Session Description Protocol (SDP)
   [RFC4566], which is commonly used to describe RTP sessions.  When SDP
   is used to specify sessions employing Opus, the mapping is as
   follows:

   o  The media type ("audio") goes in SDP "m=" as the media name.

   o  **The media subtype ("opus") goes in SDP "a=rtpmap" as the encoding
      name.  The RTP clock rate in "a=rtpmap" MUST be 48000, and the
      number of channels MUST be 2.**

Please help us fix it!

**Comment by ThomasSevestre** [comment]
@juha-h this one is already fixed on master

**Comment by juha-h** [comment]
OK, we can then close the issue.
