### ISSUE TITLE
There is no opus module for CentOS 6.8 in epel

### ISSUE THREAD

**Issue by denyspozniak** [sems-server/sems#53]
Hello!

How can I install opus module for CentOS 6 ?

[root@sems yum.repos.d]# yum search sems

sems-dsm.i686 : The state machine interpreter for SEMS
sems-g722.i686 : G.722 support for SEMS
sems-gsm.i686 : GSM support for SEMS
sems-ilbc.i686 : iLBC support for SEMS
sems-ivr.i686 : IVR functionality for SEMS
sems-python.i686 : Python bindings for SEMS
sems-speex.i686 : Speex support for SEMS
sems-xmlrpc2di.i686 : XMLRPC interface for SEMS
sems.i686 : SIP Express Media Server, an extensible SIP media server
sems-conf_auth.i686 : Conference with authorization
sems-conference.i686 : Conferencing application
sems-diameter_client.i686 : A simple DIAMETER client implementation
sems-early_announce.i686 : Early announce application
sems-mailbox.i686 : Mailbox application
sems-pin_collect.i686 : Collects a PIN

**Comment by lemenkov** [comment]
Currently (since May 10, 2017 and until November 30, 2020) RHEL 6 and therefore all derived products are in a "Maintenance Support 2 (Product retirement)" stage. I strongly recommend to switch to RHEL7 or derivatives for any new project.

CentOS 7 + EPEL 7 is fine and contains Opus module.

**Comment by hecko** [comment]
Sems in master fully supports RHEL7 and derivatives - I dont believe SEMS can be made backwards compatible at this stage. I believe this ticket can be closed.
