### ISSUE TITLE
Upper registration on Asterisk via SEMS. Loop Detected.

### ISSUE THREAD

**Issue by denyspozniak** [sems-server/sems#55]
Hello!
I use topology like this:
SIP phone (192.168.101.47) -> SEMS (192.168.100.78) -> Asterisk (192.168.101.8).
But as I see, SEMS divides Registration transactions from SIP phone on different dialogs and Asterisk can't accept such behavior.
Like below:
First dialog:     REGISTER ----------->
                      <--------Unauthorized
Second dialog: REGISTER (digest)---->
                      <----------- Forbidden

I tried to map CallID from A leg, but could not map branch and tag, otherwise Asterisk sends Loop Detected....

**reg.sbcprofile.conf**
enable_reg_caching=yes
next_hop=192.168.101.8
RURI=sip:192.168.101.8
Call-ID=$ci_leg2

I attached PCAPs to be clear (with and w/o Call-ID=$ci_leg2 option).

[PCAP_traces.zip](https://github.com/sems-server/sems/files/821146/PCAP_traces.zip)

**Comment by denyspozniak** [comment]
I attached PCAPs to be clear.

[PCAP_traces.zip](https://github.com/sems-server/sems/files/821141/PCAP_traces.zip)

**Comment by topotomaso** [comment]
I've just observed the same behaviour. Only using the option transparent_dlg_id=yes in the sbc profile conf let the registration make successful. But a transparent "id" ist not what I actually want when using sems as SBC. I'm about doing/looking for a source code fix. By the way the behaviour regarding an Invite authorization looks simular.

**Comment by topotomaso** [comment]
O.k., I think  the 'transparent_dlg_id=yes' sbc profile option together with rewriting the second call leg's callid (e.g. Call-ID=$ci_leg2) works for me. When using this option and rewriting the Call-ID of the second call-leg the 'dialogs' on both sides are definitely different even if the cseq and the from/to tags are equal.

**Comment by denyspozniak** [comment]
Hello!
Thank you so much!
It works for me also.

**Comment by juha-h** [comment]
Looks like this issue has been solved.  Closing.
