### ISSUE TITLE
180 Ringing does not pass SEMS after 181 Call being forwarded

### ISSUE THREAD

**Issue by Earn330** [sems-server/sems#64]
Hi
I'm using Version 1.7-dev-129-g7dfe676-dirty (x86_64/linux)

after getting a 181 Message that is relayed properly the following 180 Ringing Message is stuck and does not pass SEMS. In Version 1.5.1 (x86_64/linux) it is working properly

I attached a SIP Trace and debug logs of both non-working and working-call.

Greetings, Bjoern
[sems_debug_log.txt](https://github.com/sems-server/sems/files/1173436/sems_debug_log.txt)
[sems_trace.txt](https://github.com/sems-server/sems/files/1173437/sems_trace.txt)

**Comment by juha-h** [comment]
Earn330 writes:

> I'm using Version 1.7-dev-129-g7dfe676-dirty (x86_64/linux)
> 
> after getting a 181 Message that is relayed properly the following 180
> Ringing Message is stuck and does not pass SEMS. In Version 1.5.1
> (x86_64/linux) it is working properly.

There is a lot of changes in SIP dialog processing from 1.5 to 1.7.  For
some reason in 1.7, the '180 Ringing' reply is not matched to the
transaction.

-- Juha

**Comment by Earn330** [comment]
Yes, I tried Version 1.6 also and got the same wrong behaviour. So there must also be a difference between 1.5 and 1.6

BR, Bjoern

**Comment by juha-h** [comment]
In 1.5, processing of '180 Ringing' event causes forwarding of the reply:

 [#7f698f3f3700/9919] [handle_sip_reply, SipCtrlInterface.cpp:615] DEBUG: body-ct = <>
 [#7f698f3f3700/9919] [postEvent, AmEventQueue.cpp:53] DEBUG: AmEventQueue: trying to post event
 [#7f698f3f3700/9919] [postEvent, AmEventQueue.cpp:64] DEBUG: AmEventQueue: event posted
 [#7f698ffff700/9907] [run, AmSessionProcessor.cpp:97] DEBUG: running processing loop
 [#7f698f3f3700/9919] [handle_sip_reply, SipCtrlInterface.cpp:621] DEBUG: ^^ M [57830E00-597751330003969F-AC107700|3FFD9E09-5977513300039698-AC107700] ru SIP reply 180 Ringing handled ^^
 [#7f698ffff700/9907] [run, AmSessionProcessor.cpp:133] DEBUG: processing events for  up to 1 sessions
 [#7f698ffff700/9907] [processingCycle, AmSession.cpp:368] DEBUG: vv S [57830E00-597751330003969F-AC107700|3FFD9E09-5977513300039698-AC107700] Early, running, 1 UACTransPending vv
 [#7f698ffff700/9907] [processEvents, AmEventQueue.cpp:79] DEBUG: before processing event (15AmSipReplyEvent)
 [#7f698ffff700/9907] [process, AmSession.cpp:713] DEBUG: AmSession processing event
 [#7f698ffff700/9907] [onRxReply, AmSipDialog.cpp:387] DEBUG: onRxReply(rep = 180 Ringing): transaction found!
 [#7f698ffff700/9907] [onSipReply, SBC.cpp:2000] DEBUG: onSipReply: 180 Ringing (fwd=1)
 [#7f698ffff700/9907] [onSipReply, SBC.cpp:2001] DEBUG: onSipReply: content-type = 
 [#7f698ffff700/9907] [onSipReply, AmB2BSession.cpp:463] DEBUG: onSipReply: INVITE -> 180 Ringing (fwd=true), c-t=
 [#7f698ffff700/9907] [filterBody, SBC.cpp:285] DEBUG: filtering body of relayed reply 180
 [#7f698ffff700/9907] [onSipReply, AmB2BSession.cpp:484] DEBUG: relaying B2B SIP reply 180 Ringing

Whereas in 1.7, processing of '180 Ringing' event does nothing:

 [#7f1fedb4f700/10348] [handle_sip_reply, SipCtrlInterface.cpp:822] DEBUG:  body-ct = <>
 [#7f1fedb4f700/10348] [postEvent, AmEventQueue.cpp:54] DEBUG:  AmEventQueue: trying to post event
 [#7f1fedb4f700/10348] [postEvent, AmEventQueue.cpp:70] DEBUG:  AmEventQueue: event posted
 [#7f1ff0844700/10325] [run, AmSessionProcessor.cpp:97] DEBUG:  running processing loop
 [#7f1fedb4f700/10348] [handle_sip_reply, SipCtrlInterface.cpp:828] DEBUG:  ^^ M [4A5723D7-597752CA000B974F-F0945700|3C6952DA-597752CA000B9749-F0945700] ru SIP reply 180 Ringing handled ^^
 [#7f1ff0844700/10325] [run, AmSessionProcessor.cpp:133] DEBUG:  processing events for  up to 1 sessions
 [#7f1ff0844700/10325] [processingCycle, AmSession.cpp:347] DEBUG:  vv S [4A5723D7-597752CA000B974F-F0945700|3C6952DA-597752CA000B9749-F0945700] Early, running, 1 UACTransPending, 0 usages vv
 [#7f1ff0844700/10325] [processEvents, AmEventQueue.cpp:85] DEBUG:  before processing event (15AmSipReplyEvent)
 [#7f1ff0844700/10325] [process, AmSession.cpp:650] DEBUG:  AmSession processing event
 [#7f1ff0844700/10325] [processEvents, AmEventQueue.cpp:89] DEBUG:  event processed (15AmSipReplyEvent)

Perhaps you could add some debug statements and try to find why that is
the case.

-- Juha

**Comment by Earn330** [comment]
This seems not as easy as I thought. It seem no dialog handler is called, neither AmSipDialog nor AmBasicSipDialog, so I can't see what event is processed or if any event is processed. Although the log says: event processed.

**Comment by juha-h** [comment]
Earn330 writes:

> This seems not as easy as I thought. It seem no dialog handler is
> called, neither AmSipDialog nor AmBasicSipDialog, so I can't see what
> event is processed or if any event is processed. Although the log
> says: event processed.

Yes, perhaps sip_ev is null in AmSession.cpp function
AmSession::process(AmEvent* ev) test:

  AmSipEvent* sip_ev = dynamic_cast<AmSipEvent*>(ev);
  if(sip_ev){
    (*sip_ev)(dlg);
    return;
  }

and thus AmSipDialog.cpp onRxReply is not executed.

-- Juha

**Comment by Earn330** [comment]
I had a look at this and added following line:

if(sip_ev){
 DBG("SIP Event Test\n");
 (*sip_ev)(dlg); 
 return; 
}

In my log I got

[#7f3040ea0700/10780] [process, AmSession.cpp:663] DEBUG:  SIP Event Test

So I do not think sip_ev is null in this case. But I'm not good enough in programming to get the value of sip_ev or dlg into a log

**Comment by juha-h** [comment]
Earn330 writes:

> I had a look at this and added following line:
> 
> if(sip_ev){
>  DBG("SIP Event Test\n");
>  (*sip_ev)(dlg); 
>  return; 
> }
> 
> In my log I got
> 
> [#7f3040ea0700/10780] [process, AmSession.cpp:663] DEBUG:  SIP Event Test
> 
> So I do not think sip_ev is null in this case. But I'm not good enough
> in programming to get the value of sip_ev or dlg into a log

If you got this when '180 Ringing' was processed, could you add a debug
statement to the beginning of

void AmBasicSipDialog::onRxReply(const AmSipReply& reply)

and also check if execution of onRxReplySanity(reply) fails.  Perhaps
getRemoteTag() gives To tag from 181, which is not the same as To tag of
180.

In that case it looks like onRxReplySanity has a bug in it.

-- Juha

**Comment by juha-h** [comment]
I made a test where call was routed via sip proxy that replied with 181
to caller and then forwarded the call via sems sbc to callee.  180
Ringing from callee was properly forwarded all the way back to caller.

-- Juha

**Comment by juha-h** [comment]
juha-h writes:

> I made a test where call was routed via sip proxy that replied with 181
> to caller and then forwarded the call via sems sbc to callee.  180
> Ringing from callee was properly forwarded all the way back to caller.

Sorry, this was not the same as your case where 181 came to sems sbc.

-- Juha

**Comment by Earn330** [comment]
You're right. My case is a bit different. If there is just one redirect, it is not a problem - as you mention above. But we testes double redirect. And then werden need to pass a 181 through SEMS.

**Comment by juha-h** [comment]
juha-h writes:

> If you got this when '180 Ringing' was processed, could you add a debug
> statement to the beginning of
> 
> void AmBasicSipDialog::onRxReply(const AmSipReply& reply)
> 
> and also check if execution of onRxReplySanity(reply) fails.  Perhaps
> getRemoteTag() gives To tag from 181, which is not the same as To tag of
> 180.
> 
> In that case it looks like onRxReplySanity has a bug in it.

I created this setup and found that AmSipDialog::onRxReplySanity returns
false on 180 Ringing:

bool AmSipDialog::onRxReplySanity(const AmSipReply& reply)
{
  ERROR("***** AmSipDialog/onRxReplySanity %u\n", reply.code);
  if(!getRemoteTag().empty()
     && reply.to_tag != getRemoteTag()) {

    if(status == Early) {
      if(reply.code < 200 && !reply.to_tag.empty()) {
    	ERROR("***** Returning false at Early state\n");
        return false;// DROP
      }
    }
    else {
      // DROP
      ERROR("***** Returning false at non-Early state\n");
      return false;
    }
  }

  ERROR("***** Returning true\n");
  return true;
}

Aug  5 08:58:56 rautu sems[3920]: [#7fa3c7bfb700] [onRxReplySanity, AmSipDialog.cpp:337] ERROR:  ***** AmSipDialog/onRxReplySanity 100
Aug  5 08:58:56 rautu sems[3920]: [#7fa3c7bfb700] [onRxReplySanity, AmSipDialog.cpp:354] ERROR:  ***** Returning true
Aug  5 08:58:56 rautu sems[3920]: [#7fa3c7bfb700] [onRxReplySanity, AmSipDialog.cpp:337] ERROR:  ***** AmSipDialog/onRxReplySanity 181
Aug  5 08:58:56 rautu sems[3920]: [#7fa3c7bfb700] [onRxReplySanity, AmSipDialog.cpp:354] ERROR:  ***** Returning true
Aug  5 08:58:57 rautu sems[3920]: [#7fa3c7bfb700] [onRxReplySanity, AmSipDialog.cpp:337] ERROR:  ***** AmSipDialog/onRxReplySanity 180
Aug  5 08:58:57 rautu sems[3920]: [#7fa3c7bfb700] [onRxReplySanity, AmSipDialog.cpp:343] ERROR:  ***** Returning false at Early state

I then checked what kind of 1xx response codes there is:

1xx—Provisional Responses

100 Trying
    Extended search being performed may take a significant time so a
    forking proxy must send a 100 Trying response.[1]:§21.1.1
180 Ringing
    Destination user agent received INVITE, and is alerting user of
    call.[1]:§21.1.2 
181 Call is Being Forwarded
    Servers can optionally send this response to indicate a call is being forwarded.[1]:§21.1.3
182 Queued
    Indicates that the destination was temporarily unavailable, so the
    server has queued the call until the destination is available. A
    server may send multiple 182 responses to update progress of the
    queue.[1]:§21.1.4 
183 Session in Progress
    This response may be used to send extra information for a call which
    is still being set up.[1]:§21.1.5 
199 Early Dialog Terminated
    Can be used by User Agent Server to indicate to upstream SIP
    entities (including the User Agent Client (UAC)) that an early
    dialog has been terminated.[3]

Out of these 181 and 182 should not (in my opinion) cause the state of
the dialog to go to Early state.

Comments?

-- Juha

**Comment by juha-h** [comment]
Try with this patch.

-- Juha

-------------------------------------------------------------------------

*** /usr/src/orig/sems/core/AmSipDialog.cpp	2017-08-05 08:50:56.494412516 +0300
--- AmSipDialog.cpp	2017-08-05 11:35:40.638639840 +0300
***************
*** 364,370 ****
      case Trying:
      case Proceeding:
        if(reply.code < 200){
! 	if(reply.code == 100 || reply.to_tag.empty())
  	  setStatus(Proceeding);
  	else {
  	  setStatus(Early);
--- 369,376 ----
      case Trying:
      case Proceeding:
        if(reply.code < 200){
! 	if (((reply.code == 100) || (reply.code == 181) || (reply.code == 182))
! 	    || reply.to_tag.empty())
  	  setStatus(Proceeding);
  	else {
  	  setStatus(Early);

**Comment by Earn330** [comment]
I have tried your patch in our lab and it seems to work. I will make further test but I think I it's ok now. Thank you for your help

BR, Bjoern
