### ISSUE TITLE
sems: 1.7.0-dev Call-ID generation not UUID like described in docs

### ISSUE THREAD

**Issue by dunst0** [sems-server/sems#67]
Is there something special to know? Because for me the generate Call-ID is not like described in docs with UUID.

`Call-ID: 27074B0D-59B176EF00068875-8636A700`

https://github.com/sems-server/sems/blob/942da3d6638be74b2042c297369ce8b73f79a367/doc/Readme.sbc.txt#L277-L278

```
# uname -a
Linux media1.voice.dev.host 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Its a CentOS.
```

```
# sems -v
Sip Express Media Server (1.7.0-dev (x86_64/Linux))
```

**Comment by juha-h** [comment]
Rick writes:

> Is there something special to know? Because for me the generate
> Call-ID is not like described in docs with UUID. 
> 
> `Call-ID: 27074B0D-59B176EF00068875-8636A700`
> 
> https://github.com/sems-server/sems/blob/942da3d6638be74b2042c297369ce8b73f79a367/doc/Readme.sbc.txt#L277-L278

Looks like a bug in the doc.  It is not a good idea to include host-ip
in Call-ID.

-- Juha

**Comment by dunst0** [comment]
How is it with the uniqueness when having multiple sems server handling traffic?

https://github.com/sems-server/sems/blob/942da3d6638be74b2042c297369ce8b73f79a367/core/AmSession.cpp#L485-L496

**Comment by juha-h** [comment]
Rick writes:

> How is it with the uniqueness when having multiple sems server
> handling traffic?
> 
> https://github.com/sems-server/sems/blob/942da3d6638be74b2042c297369ce8b73f79a367/core/AmSession.cpp#L485-L496

I don't know (haven't studied the code), but adding any IP to call-id is
very bad idea.

-- Juha

**Comment by dunst0** [comment]
@juha-h  Thank you for your response.
