### ISSUE TITLE
sems-1.7.0-dev: Session Timer plugin refresher problem

### ISSUE THREAD

**Issue by dunst0** [sems-server/sems#68]
In the following setup the sst plugin does give me a hard time.

Phone --> Proxy --> SBC(sst enabled) --> Proxy --> SBC(sst enabled) --> Proxy --> Phone

The call will become teared down by one of the sbc becaus of pendig request, cseq missmatch and timeouts, in this setup. It seems that there is some quirky stuff is happening when determine session refresher.

__call flow:__
```
        ──────────┬─────────          ──────────┬─────────          ──────────┬─────────
20:54:03.873249   │ ─────── INVITE (SDP) ─────> │                             │
20:54:03.892432   │ <───── 100 Connecting ───── │                             │
20:54:03.907397   │                             │ ─────── INVITE (SDP) ─────> │
20:54:03.909281   │                             │ <─────── 100 Trying ─────── │
20:54:04.399954   │                             │ <─────── 180 Ringing ────── │
20:54:04.400700   │ <─────── 180 Ringing ────── │                             │
20:54:06.027741   │                             │ <────── 200 OK (SDP) ────── │
20:54:06.029266   │ <────── 200 OK (SDP) ────── │                             │
20:54:06.060060   │ ──────────── ACK ─────────> │                             │
20:54:06.069732   │                             │ ──────────── ACK ─────────> │
```
__a-leg side of sems:__
```
INVITE sip:.... SIP/2.0
....
Supported: timer
Session-Expires: 120
Min-SE: 90
```

```
SIP/2.0 200 OK
....
Supported: replaces, 100rel, timer, norefersub
Require: timer
Session-Expires: 120;refresher=uas    <-- shouldn't this be uac?
```

__b-leg side of sems:__

```
INVITE sip:.... SIP/2.0
....
Supported: timer
Session-Expires: 120
Min-SE: 90
```

```
SIP/2.0 200 OK
....
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 120;refresher=uac
Require: timer
```

Btw if I overwrite the refresher=uas with uac, the session kept running.

**Comment by juha-h** [comment]
Rick writes:

> __a-leg side of sems:__
> ```
> INVITE sip:.... SIP/2.0
> ....
> Supported: timer
> Session-Expires: 120
> Min-SE: 90
> ```
> 
> 
> ```
> SIP/2.0 200 OK
> ....
> Supported: replaces, 100rel, timer, norefersub
> Require: timer
> Session-Expires: 120;refresher=uas    <-- shouldn't this be uac?

It can be uas. See Table 2 of rfc4028.

-- Juha

**Comment by dunst0** [comment]
Just curious has anyone else have to send talking to each other because if that's the way it should implemented I must do something else wrong. Because the B2BUA are not doing the correct refreshing of the session, because the clients in the call seem to have a different opinion how's doing the refresh.

**Comment by dunst0** [comment]
@juha-h Shouldn't sems just stay passiv if one of the sides doing session refresh?
I got a call flow where the other side says in 200 OK,  Session-Expires: 120;refresher=uas
But the sems is doing the refresh and because of that he responses Request Pending when the b leg call sends it session refresh.

**Comment by juha-h** [comment]
It is hard to figure out what is going on based on that description.  Make a test call where the problem occurs, place ngrep outputs of both sides of the call to pastebin  or somewhere, and point out where exactly sems is behaving incorrectly.

**Comment by dunst0** [comment]
I will try to make a sip trace but must replace the actual telephone numbers for that trace. To not leak telephone numbers.

**Comment by dunst0** [comment]
I will close this issue for now.
