### ISSUE TITLE
Relay Problems on CFNR scenarios

### ISSUE THREAD

**Issue by Earn330** [sems-server/sems#75]
We have a SEMS running as SBC. After that comes a Kamailio that does a lot of class5 features for our customers. One of them is CFNR. This is some kind of problematic as the call may be in proceeding or even early state so it has an to-tag and after a while the call is routed to an other destination where it gets another one.
In our case the caller gets a 180 ringing from the callee. After a while the call is forwarded to an other destination where it send a 183 message to the caller. But this message never reaches it destination as SEMS does not relay this message. I think it is because of the different to-tag.
This is problematic as the caller is still at the wrong ringback and when he cancels the call, the call gets stuck in sems.
I hope you will understand what my problem is.

BR, Bjoern

**Comment by Earn330** [comment]
To give you something to your hands I'll give you a log and a pcap. Please excuse this setup but I can't simplify this to you. The faulty point comes after the 180 ringing that goes to 192.168.253.74. That's the ringback from the first destination. After the destination changes I got a 183 Session Progress. This is the packet, that is not relayed to 192.168.253.74 but i has to. Also the message following (180) hast to be relayed. Both of them stuck.

[sems_debug_cfnr.txt](https://github.com/sems-server/sems/files/1571765/sems_debug_cfnr.txt)

[sems-1.7-dev-cfnr-faulty.pcap.pcapng.zip](https://github.com/sems-server/sems/files/1571769/sems-1.7-dev-cfnr-faulty.pcap.pcapng.zip)

**Comment by juha-h** [comment]
Earn330 writes:

> To give you something to your hands I'll give you a log and a
> pcap. Please excuse this setup but I can't simplify this to you. The
> faulty point comes after the 180 ringing that goes to
> 192.168.253.74. That's the ringback from the first destination. After
> the destination changes I got a 183 Session Progress. This is the
> packet, that is not relayed to 192.168.253.74 but i has to. Also the
> message following (180) hast to be relayed. Both of them stuck.

I tried with a simple b2b dsm app. First callee replied with 180 Ringing
and sems passed that to caller.  When there was no answer soon enough,
my sip proxy canceled that leg and tried a second callee.  When the
second callee replied with 180 Ringing, sems did not pass that to the
caller, but did pass the subsequent 200 OK with the same To tag as in
the original 180 Ringing.  Nothing got stuck anywhere.

I don't currently have a SIP UA that could give 183 Session Progress
response. If sems would not pass that to the caller, I would say that it
is a missing feature rather than a bug.

-- Juha

**Comment by Earn330** [comment]
> When the second callee replied with 180 Ringing, sems did not pass that to the caller,

This is the problem, because it may also be 183 early media, that should be passed. Also it leads to the problem below

>  but did pass the subsequent 200 OK with the same To tag as in the original 180 Ringing

This is also right. A call can be established. And everything is ok when call is teared by a BYE. The Leg get stuck when the call is not established but canceled by the caller, although the call seems to be canceled on caller and callee side

**Comment by juha-h** [comment]
Earn330 writes:

> > When the second callee replied with 180 Ringing, sems did not pass
> > that to the caller, 
> 
> This is the problem, because it may also be 183 early media, that
> should be passed. Also it leads to the problem below 
> 
> >  but did pass the subsequent 200 OK with the same To tag as in the
> >  original 180 Ringing 
> 
> This is also right. A call can be established. And everything is ok
> when call is teared by a BYE. The Leg get stuck when the call is not
> established but canceled by the caller, although the call seems to be
> canceled on caller and callee side

I tried that too.  The call was not cleared immediately after caller
canceled, but got cleared when the session timer hit.

-- Juha

**Comment by Earn330** [comment]
Session timer is a problem as I faced a lot clients that do not work properly with session timers. This leads to customer complaints about broken down calls. So session timer is no options for us :(

**Comment by juha-h** [comment]
Without using session timer, I cannot see how you can prevent calls from
not getting cleared up.

-- Juha

**Comment by Earn330** [comment]
I think it would help if the ringback from the second callee would pass sems as then the call is correctly setted up from sems point of view

**Comment by Earn330** [comment]
I also made some tests today with a session timer of 1800 Seconds. The left call leg was still there after 37 minutes. So session timer seems not to be solution at all

**Comment by juha-h** [comment]
Looks like sems does not allow To tag to change after 180 or 183 has
been received, i.e., an INVITE cannot create more than one dialog.

-- Juha

----------------------------------------------------------------------

bool AmSipDialog::onRxReplyStatus(const AmSipReply& reply)
{
  // rfc3261 12.1
  // Dialog established only by 101-199 or 2xx 
  // responses to INVITE

  if(reply.cseq_method == SIP_METH_INVITE) {

    switch(status){

    case Trying:
    case Proceeding:
      if(reply.code < 200){
	// Do not go to Early state if To tag can still change
	// Otherwise reply check will fail
	if (((reply.code == 100) || (reply.code == 181) || (reply.code == 182))
	    || reply.to_tag.empty())
	  setStatus(Proceeding);
	else {
	  setStatus(Early);
	  setRemoteTag(reply.to_tag);
	  setRouteSet(reply.route);
	}
      }

**Comment by juha-h** [comment]
Earn330 writes:

> I also made some tests today with a session timer of 1800 Seconds. The
> left call leg was still there after 37 minutes. So session timer seems
> not to be solution at all

I have

session_expires=1800
minimum_timer=90
maximum_timer=3600

and after caller canceled, the session got cleared after about 30
minutes.

-- Juha

Dec 22 04:12:07 lohi sems[29001]: [#7fec7e381700] [on_read, tcp_trsp.cpp:348] DEBUG:  received: <CANCEL sip:jh@test.tutpro.com;appl=b2b-relay SIP/2.0..Via: SIP/2.0/TCP 127.0.0.1:5070;branch=z9hG4bK8e95.f9dadd49d3bb1c0efb85b76feae13df1.0;i=c1..Max-Forwards: 69..To: <sip:jh@ex.test.tutpro.com;appl=b2b-relay>..From: <sip:test@test.tutpro.com>;tag=8104ec937fccf0a1..Call-ID: 5b12b023f1b671fd..CSeq: 15904 CANCEL..Content-Length: 0....>
...
Dec 22 04:41:51 lohi sems[29001]: [#7fec7de7c700] [retryRefreshTimer, SessionTimer.cpp:417] DEBUG:  Retrying session refresh timer: T-2s, tag '3407EEA4-5A3C69E90003CF60-7E381700'
Dec 22 04:41:51 lohi sems[29001]: [#7fec7de7c700] [setTimer, AmSession.cpp:1245] DEBUG:  setting timer -2 with timeout 2.000000
Dec 22 04:41:51 lohi sems[29001]: [#7fec7de7c700] [processingCycle, AmSession.cpp:416] DEBUG:  ^^ S [5b12b023f1b671fd|3407EEA4-5A3C69E90003CF60-7E381700] Cancelling, stopped, 0 UACTransPending, 0 usages ^^
Dec 22 04:41:53 lohi sems[29001]: [#7fec9067f700] [app_timer_cb, AmAppTimer.cpp:92] DEBUG:  timer fired: -1 for '3407EEA4-5A3C69E90003CF60-7E381700'
Dec 22 04:41:53 lohi sems[29001]: [#7fec9067f700] [app_timer_cb, AmAppTimer.cpp:92] DEBUG:  timer fired: -2 for '3407EEA4-5A3C69E90003CF60-7E381700'
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [processingCycle, AmSession.cpp:347] DEBUG:  vv S [5b12b023f1b671fd|3407EEA4-5A3C69E90003CF60-7E381700] Cancelling, stopped, 0 UACTransPending, 0 usages vv
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [process, DSMCall.cpp:485] DEBUG:  DSMCall::process
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:616] DEBUG:  o v DSM current state 'end', processing 'Timer' event v
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:624] DEBUG:   > state 'end'
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:630] DEBUG:   ...checking transition 'bye recvd'
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:731] DEBUG:  o ^ DSM event processed/consumed; current state 'end' ^
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [process, SessionTimer.cpp:73] DEBUG:  received timeout Event with ID -1
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:616] DEBUG:  o v DSM current state 'end', processing 'SessionTimeout' event v
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:624] DEBUG:   > state 'end'
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:630] DEBUG:   ...checking transition 'bye recvd'
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [runEvent, DSMStateEngine.cpp:731] DEBUG:  o ^ DSM event processed/consumed; current state 'end' ^
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [onSessionTimeout, AmB2BSession.cpp:644] DEBUG:  Session Timer: Timeout, ending other leg
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [relayEvent, AmB2BSession.cpp:591] DEBUG:  AmB2BSession::relayEvent: to other_id='53E95B43-5A3C69E90003F1F8-7DE7C700'
Dec 22 04:41:53 lohi sems[29001]: [#7fec7de7c700] [onSessionTimeout, AmSession.cpp:1049] DEBUG:  Session Timer: Timeout, ending session.
...

**Comment by Earn330** [comment]
First of all, I hope you had some nice holidays. As I was on vacation for some time, I had a clearer look at the problem. It is not solved by setting a session timer as the call is not established when it is canceled. But I found a bug in your code 

> if (((reply.code == 100) || (reply.code == 181) || (reply.code == 182)) || reply.to_tag.empty())

Here you missed 180 as reply code. So at the first 180 reply, the call goes into early state. As a consequence after changing the destination and getting a second 1xx reply this case is not matching.
So I edited the line as following.

`if (((reply.code == 100) || (reply.code == 180) || (reply.code == 181) || (reply.code == 182) || (reply.code == 183)) || reply.to_tag.empty()){`

As you can see, I added 180 as reply and also 183. Now the call stays in proceeding state and all 1xx replies are relayed properly. When getting a 200 reply the call goes into early state and in result of this in connected state.

As result there are no hanging calls legs when canceling the call.

**Comment by juha-h** [comment]
Unless someone opposes, I'll make the above change in a couple of days.

**Comment by juha-h** [comment]
Added 180 reply to the ones that still allow To tag to change.
