### ISSUE TITLE
SEMS SBC has no call control modules when installed from EPEL7

### ISSUE THREAD

**Issue by ozymike** [sems-server/sems#91]
Hi team,

just installed the sems package from EPEL on CentOS7. Everything works fine, however none of the call control modules get installed.
Am I missing something?

Cheers
Michael

**Comment by juha-h** [comment]
ozymike writes:

> just installed the sems package from EPEL. Everything works fine,
> however none of the call control modules get installed. 
> Am I missing something?

I don't know anything about rpm, but looks like pkg/rpm directory (file
sems.spec) has not been updated since sbc module was developed.

I suggest you try to find someone to maintain sems rpm packaging.

-- Juha

**Comment by lemenkov** [comment]
> Hi team,
> 
> just installed the sems package from EPEL on CentOS7. Everything works fine, however none of the call control modules get installed.
> Am I missing something?
> 
> Cheers
> Michael

Yes, it misses them accidentally. I'm working on adding them.

**Comment by lemenkov** [comment]
Fixed with this build:

* https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-87278c8214

@juha-h I think this can be closed now.

**Comment by juha-h** [comment]
OK
