### ISSUE TITLE
Max-Forward is not decreased

### ISSUE THREAD

**Issue by Earn330** [sems-server/sems#93]
We realized that the Max-Forward Header is not decreased when a call is passing the sbc module of sems.

Instead the Header is replaced with a default value (70). This may result in unlimited routing attemps. SEMS should be aware of this header. Can you please provide a patch that will fix this behaviour or give me a hint where I can patch this?

Our Version is Sip Express Media Server (1.7-dev-62-gb28d307-dirty (x86_64/linux))

[debug.txt](https://github.com/sems-server/sems/files/2401594/debug.txt)

BR, Bjoern

**Comment by Earn330** [comment]
Sorry, I think I understand what you are trying to do, but this is a little bit too much for me. Would you please be so kind to make some code snippets that I can just insert?

**Comment by juha-h** [comment]
There needs to be an sbc and/or sbc profile configuration variable that controls this behavior.

**Comment by Earn330** [comment]
I think it must be configurable as loop detection needs to be possible according to rfc 7332

**Comment by ThomasSevestre** [comment]
Sorry, I don't know how to make it configurable

**Comment by juha-h** [comment]
Usually it is a good idea to default to existing behavior and allow the new one based on configuration.  But since RFC 7332 sort of mandates decrementing of max forwards value, perhaps we can just change the current behavior accordingly.  Create a pull request and I'll give it a try.

**Comment by juha-h** [comment]
@ThomasSevestre, could you check if pull request https://github.com/sems-server/sems/pull/94 makes sense to you.

**Comment by ThomasSevestre** [comment]
@juha-h it was my first guess but it actually doesn't work with SBC module. I have a working patch, I'll make it a PR in the next days
On second thought I'm not sure it is a good idea do decrease Max Forwards in SBC module since it can be used to hide topology

**Comment by juha-h** [comment]
ThomasSevestre writes:

> @juha-h it was my first guess but it actually doesn't work with SBC
> module.

Yes, I figured that out.  SBC module does not call
AmB2BSession::onB2BEvent().  My code works OK with applications that
don't use SBC plugin.

> I have a working patch, I'll make it a PR in the next days 
> On second thought I'm not sure it is a good idea do decrease Max
> Forwards in SBC module since it can be used to hide topology.

I agree and therefore I suggested to make the feature configurable in
the profile.

**Comment by Earn330** [comment]
Hi @ThomasSevestre 

have you something new for me? 

BR, Bjoern

**Comment by Earn330** [comment]
Hi 

is a patch in sight of view? I'll have a patch day during the next week, and it would be very cool if I can apply it to our plattform. The patch alone will satisfy me, as I don't need the ability to configure the max_forward feature in our profiles. Please be so kind and provide your patch.

BR, Bjoern

**Comment by ThomasSevestre** [comment]
Hi
Here is a patch [https://gist.github.com/ThomasSevestre/df9315c2152f12dafb527d67379bd03b](url)
Be carefull it is barely tested
Regards

**Comment by Earn330** [comment]
Thank you. I'll make some tests during the next days and report my results.

BR, Bjoern

**Comment by juha-h** [comment]
ThomasSevestre writes:

> Here is a patch [https://gist.github.com/ThomasSevestre/df9315c2152f12dafb527d67379bd03b](url)

Thanks for the patch.  If max_forwards is set in config, sems should not
send request out with bigger value.

I have in AmB2BSession.cpp:

 if (req_ev->req.max_forwards > AmConfig::MaxForwards) {
	    req_ev->req.max_forwards = AmConfig::MaxForwards;
	  } else {
	    req_ev->req.max_forwards--;
	  }

**Comment by juha-h** [comment]
ThomasSevestre writes:

> Here is a patch
> [https://gist.github.com/ThomasSevestre/df9315c2152f12dafb527d67379bd03b](url)

I included your changes to sems/max_forwards branch and did some tests
that used SBC call control module.  Max-Forwards value was either
decremented or set to max_forwards config value (if incoming value was
greater).

Decreasing of Max-Forwards in DSM applications would still need to be
implementing.

**Comment by Earn330** [comment]
I also make some test at the moment. Decrementing max_forwards is working finde with sbc module. Unfortunately a call is not stopped when an INVITE with Max-Forwards=0 is received. Instead SEMS is relaying the INVITE with Max-Forwards: 70, so the loop is not stopping

**Comment by juha-h** [comment]
Earn330 writes:

> I also make some test at the moment. Decrementing max_forwards is
> working finde with sbc module. Unfortunately a call is not stopped
> when an INVITE with Max-Forwards=0 is received. Instead SEMS is
> relaying the INVITE with Max-Forwards: 70, so the loop is not
> stopping.

I too notice that with SBC.  It works OK without SBC, e.g., using
early_announce app.

-- Juha

**Comment by juha-h** [comment]
juha-h writes:
> Earn330 writes:
> 
> > I also make some test at the moment. Decrementing max_forwards is
> > working finde with sbc module. Unfortunately a call is not stopped
> > when an INVITE with Max-Forwards=0 is received. Instead SEMS is
> > relaying the INVITE with Max-Forwards: 70, so the loop is not
> > stopping.
> 
> I too notice that with SBC.  It works OK without SBC, e.g., using
> early_announce app.

The check is done in AmB2BSession::onB2BEvent(B2BEvent* ev)
B2BSipRequest event handling. When SBC is used, that event is not
invoked.

**Comment by juha-h** [comment]
juha-h writes:

> The check is done in AmB2BSession::onB2BEvent(B2BEvent* ev)
> B2BSipRequest event handling. When SBC is used, that event is not
> invoked.

I added Max-Forwards check to AmBasicSipDialog.  Zero is now detected in
my SBC tests. Try with latest:

https://github.com/sems-server/sems/tree/max_forwards

**Comment by juha-h** [comment]
When Max-Forwards is checked during sanity checking of incoming request,
it applies both to requests that are terminated to sems and to those
that sems forwards.

If it is not easy to check Max-Forwards in SBC application, then I my
opinion the above is better than no check at all.

-- Juha

**Comment by juha-h** [comment]
I read sems source code and it turned out that in order to be able to
decrease Max-Forwards in IVR and DSM applications, max_forwards param
would need to be added to function
```
string AmUAC::dialout(const string& user,
		      const string& app_name,
		      const string& r_uri, 
		      const string& from,
		      const string& from_uri,
		      const string& to,
		      const string& local_tag,
		      const string& hdrs,
		      AmArg*  session_params)
```
Default value of the param would be -1.

**Comment by Earn330** [comment]
I made some tests today. I think I found a bug. After sems finds Max-Forwards: 0 it replies correctly with 483 Too many hops. 
All call-legs are teared down except one. The strange thing is that it is alway an a-leg and i never find a corresponding b-leg for this call. I tried to get all call-legs while the call is proceeding. This may be also the reason why this leg is not cleared, as there is no b-leg.
Does this occur in your tests too?

**Comment by juha-h** [comment]
Earn330 writes:

> All call-legs are teared down except one. The strange thing is that it
> is alway an a-leg and i never find a corresponding b-leg for this
> call. I tried to get all call-legs while the call is proceeding. This
> may be also the reason why this leg is not cleared, as there is no
> b-leg.
> Does this occur in your tests too?

Are you looping the same call back to sems many times?

**Comment by Earn330** [comment]
Yes I do this.

So routing goes 

UAC -> Proxy -> SEMS -> UAS (loop begins here) -> SEMS -> Proxy -> SEMS -> UAS -> SEMS -> Proxy -> SEMS (483 Too many hops)

**Comment by Earn330** [comment]
i think the the last hop may be a problem, as the sbc module recived the call but does not relay it. Instead it is replied with 483. Maybe there is something to do with the a-leg.

**Comment by juha-h** [comment]
Earn330 writes:

> So routing goes 
> 
> UAC -> Proxy -> SEMS -> UAS (loop begins here) -> SEMS -> Proxy -> SEMS -> UAS -> SEMS -> Proxy -> SEMS (483 Too many hops)

I don't have such a test setup.

**Comment by Earn330** [comment]
I'm testing at the moment but it look promising. Thank you :+1:

**Comment by juha-h** [comment]
Earn330 writes:

> I'm testing at the moment but it look promising. Thank you :+1:

Tell when you are confident that be fixes work and I'll commit
max_forwards branch to master.

**Comment by juha-h** [comment]
juha-h writes:

> Earn330 writes:
> 
> > I'm testing at the moment but it look promising. Thank you :+1:
> 
> Tell when you are confident that be fixes work and I'll commit
> max_forwards branch to master.

I would like to move on with this.  Is it OK that I pull max_forwards
branch to master?

**Comment by Earn330** [comment]
Hi @juha-h 
I made a lot of tests and I could not find any errors any more. So I think you pull max_forward branch to master.

Thank you all :1st_place_medal: 

BR, Bjoern

**Comment by juha-h** [comment]
Fiexed by https://github.com/sems-server/sems/commit/732438f3cc5496235105fc4413e6a543bc077a95. Thanks to @ThomasSevestre for SBC help.
