### ISSUE TITLE
[SEMS] Fedora build sems-1.6.0-15.fc30 is failed

### ISSUE THREAD

**Issue by denyspozniak** [sems-server/sems#96]
Hello!
@lemenkov could you check why build **sems-1.6.0-15.fc30** was failed?
[](https://koji.fedoraproject.org/koji/buildinfo?buildID=1147892)

**Comment by denyspozniak** [comment]
Also maybe you have spec file for **sems-1.7** ?

**Comment by lemenkov** [comment]
@denyspozniak hey! I'll do in a mean time.
