### ISSUE TITLE
[SEMS 1.7] CentOS 7. Compile error.

### ISSUE THREAD

**Issue by denyspozniak** [sems-server/sems#97]
Hello!
Please help me to compile sems 1.7-dev-214-gdf92a7e  for CentOS 7:

```
make[3]: Entering directory `/usr/src/sipwise/sems/core/plug-in/codec2'
make[3]: *** No rule to make target `all'.  Stop.
make[3]: Leaving directory `/usr/src/sipwise/sems/core/plug-in/codec2'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/usr/src/sipwise/sems/core/plug-in'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/usr/src/sipwise/sems/core'
make: *** [modules] Error 2

```
```
[root@sems]# rpm -qa | grep codec2
libcodec2-2.59-1.el7.x86_64
libcodec2-devel-2.59-1.el7.x86_64
```

Also I tried with codec2-devel, result was the same.
```
[root@sems]# rpm -qa | grep codec2
codec2-0.8.1-1.el7.x86_64
codec2-devel-0.8.1-1.el7.x86_64
```

**Comment by skrusty** [comment]
I am also getting this on Ubuntu

**Comment by denyspozniak** [comment]
I could install on Ubuntu according to the **.travis.yml**.

```
root@sems:/usr/src/sems# sems -v
Sip Express Media Server (1.7.0-dev (x86_64/Linux))
```

```
root@sems# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

**Comment by skrusty** [comment]
Yes, i followed the travis file and it works, but that downloads a specific version of Codec2. Using the pre-build and post-buidl scripts, i can compile this on ubuntu. However, the make file fails, and the docs don't specifically state you need to download and install codec2, as per: 

```
wget https://freedv.com/wp-content/uploads/sites/8/2017/10/codec2-0.7.tar.xz
        - tar -xvf codec2-0.7.tar.xz
        - pushd codec2-0.7 && mkdir build && pushd build && cmake -DCMAKE_INSTALL_PREFIX=/usr ../ && make && sudo make install && popd && popd
```

**Comment by denyspozniak** [comment]
Yes, it should work, I could compile when manually modified file ../sems/core/plug-in/CMakeLists.txt and deleted folder codec2.

**Comment by skrusty** [comment]
Not sure this should be closed, technically make doesn't work without manually editing the build processes, based on the build guide on here.
